# Generated by Django 4.2.11 on 2025-05-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seats_reserved",
                    models.PositiveIntegerField(help_text="Number of seats reserved"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of the reservation",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the reservation",
                        max_length=20,
                    ),
                ),
                (
                    "reservation_date",
                    models.DateField(help_text="Date of the reservation"),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Table that was reserved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="tables.table",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the reservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reservation_date"],
                "unique_together": {("table", "reservation_date", "status")},
            },
        ),
    ]
